version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ../backend/.env
  web:
    depends_on:
      - db
    restart: always
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    env_file:
      - ../backend/.env
    ports:
      - "8000:8000"



volumes:
  postgres_data:
  static_value:
  media_value: