# Generated by Django 2.2.6 on 2022-02-23 20:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('color', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Enter valid hex color number', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Color')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Label')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='what is the note about', max_length=15, verbose_name='about')),
                ('text', models.TextField(help_text='the main content of the post', verbose_name='Text')),
                ('date_create', models.DateTimeField(auto_now_add=True, help_text='Date note create', verbose_name='Date_create')),
                ('image', models.ImageField(blank=True, help_text='Upload image', null=True, upload_to='posts/', verbose_name='Image')),
                ('author', models.ForeignKey(help_text='author name', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='author name')),
                ('tags', models.ManyToManyField(related_name='posts', to='notes.Tag', verbose_name='tags')),
            ],
        ),
    ]
