# Generated by Django 3.0.5 on 2022-03-04 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20220225_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes_to_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(help_text='author name', on_delete=django.db.models.deletion.CASCADE, related_name='Notes_to_tags', to='notes.Note', verbose_name='author name')),
                ('tags', models.ForeignKey(help_text='author name', on_delete=django.db.models.deletion.CASCADE, related_name='Notes_to_tags', to='notes.Tag', verbose_name='author name')),
            ],
        ),
    ]
