# Generated by Django 3.0.5 on 2022-03-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notes_to_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes_to_tag',
        ),
    ]
